updates to amplify app and pipeline

diff --git a/.github/workflows/aws-pubsub.yaml b/.github/workflows/aws-pubsub.yaml
--- a/.github/workflows/aws-pubsub.yaml
+++ b/.github/workflows/aws-pubsub.yaml
@@ -13,7 +13,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
       # Install Diagrid CLI
       - name: Install Diagrid CLI
         run: |
@@ -38,7 +38,7 @@ jobs:
 
             # Temporarily disable bash -e for the diagrid command
             set +e
-            output=$(diagrid appid create -p test-aws "$service_name" 2>&1)
+            output=$(diagrid appid create -p ${{vars.DIAGRID_PROJECT}} "$service_name" 2>&1)
             exit_code=$?
             set -e
 
@@ -68,18 +68,19 @@ jobs:
               --attribute-definitions AttributeName=key,AttributeType=S \
               --key-schema AttributeName=key,KeyType=HASH \
               --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 2>&1)
+            exit_code=$?
             set -e
             
             # Check if the error is about the table already existing
             if echo "$output" | grep -q "ResourceInUseException"; then
               echo "Table already exists for $table_name, continuing..."
               continue
-            elif [ $? -ne 0 ]; then
+            elif [ $exit_code -ne 0 ]; then
               echo "An error occurred while creating table $table_name: $output"
               exit 1
             fi
             
-            sleep 10
+            sleep 5
           done
 
       - name: Check App Status
@@ -93,7 +94,7 @@ jobs:
         run: |
           # Temporarily disable bash -e for the component create command
           set +e
-          output=$(diagrid component create aws-pubsub --type pubsub.aws.snssqs --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ secrets.AWS_DEFAULT_REGION }} --project ${{ vars.DIAGRID_PROJECT }})
+          output=$(diagrid component create aws-pubsub --type pubsub.aws.snssqs --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ vars.AWS_DEFAULT_REGION }} --project ${{ vars.DIAGRID_PROJECT }})
           set -e
 
           # Check if the output contains "Resource already exists"
@@ -113,7 +114,7 @@ jobs:
             
              # Temporarily disable bash -e for the diagrid command
             set +e
-            output=$(diagrid component create $table_name --type state.aws.dynamodb --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ secrets.AWS_DEFAULT_REGION }} --metadata table=$table_name --scopes $service_name --project ${{vars.DIAGRID_PROJECT}})
+            output=$(diagrid component create $table_name --type state.aws.dynamodb --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ vars.AWS_DEFAULT_REGION }} --metadata table=$table_name --scopes $service_name --project ${{vars.DIAGRID_PROJECT}})
             exit_code=$?
             set -e
 
@@ -126,7 +127,7 @@ jobs:
               exit 1
             fi
             
-            sleep 10
+            sleep 5
 
           done
 
@@ -182,67 +183,68 @@ jobs:
           for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             
-            # Fetch the Diagrid app identity information in JSON format
-            # Error handling if diagrid appid get command fails
+            # Fetch the Diagrid App ID information in JSON format
+
             if ! diagrid_output=$(diagrid appid get $service_name -o json 2>/dev/null); then
-              echo "Error: Failed to retrieve Diagrid app identity for $service_name"
+              echo "Error: Failed to retrieve Diagrid App ID for $service_name"
               continue  # Skip this service and move to the next one
             fi
             
-            # Extract the apiToken using jq from the Diagrid output
+            # Extract the API Token using jq from the Diagrid output
             api_token=$(echo $diagrid_output | jq -r '.status.apiToken')
             
             # Check if apiToken is null or empty
             if [ -z "$api_token" ] || [ "$api_token" == "null" ]; then
-              echo "Error: No valid apiToken found for $service_name"
+              echo "Error: No API Token found for $service_name"
               continue  # Skip this service and move to the next one
             fi
             
             echo "API Token for $service_name: $api_token"
             
-            # Create a JSON object with the service, apiToken, http_url, and grpc_url
+            # Create a JSON object with the service, api_token, http_url, and grpc_url
             json_object=$(jq -n --arg service "$service_name" \
-                               --arg apiToken "$api_token" \
+                               --arg api_token "$api_token" \
                                --arg http_url "$http_url" \
                                --arg grpc_url "$grpc_url" \
-                               '{service: $service, apiToken: $apiToken, http_url: $http_url, grpc_url: $grpc_url}')
+                               '{service: $service, api_token: $api_token, http_url: $http_url, grpc_url: $grpc_url}')
             
             # Add the JSON object to the array
             json_array=$(echo $json_array | jq --argjson obj "$json_object" '. += [$obj]')
           done
 
           # Save the JSON array to a file
-          echo $json_array | jq . > cdk-infra/service_tokens.json
+          echo $json_array | jq . > ./aws-pubsub/cdk-infra/service_tokens.json
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "service_tokens<<$EOF" >> $GITHUB_OUTPUT
           echo "$json_array" >> $GITHUB_OUTPUT
           echo "$EOF" >> $GITHUB_OUTPUT
 
-          cat cdk-infra/service_tokens.json
+          cat ./aws-pubsub/cdk-infra/service_tokens.json
 
       - name: Upload service_tokens.json
         uses: actions/upload-artifact@v4
         with:
           name: service_tokens
-          path: cdk-infra/service_tokens.json
+          path: ./aws-pubsub/cdk-infra/service_tokens.json
       - name: Install other dependencies
         run: |
           npm install
-        working-directory: ./cdk-infra
+        working-directory: ./aws-pubsub/cdk-infra
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@master
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
 
       # Download the service_tokens.json artifact
       - name: Download service_tokens.json
         uses: actions/download-artifact@v4
         with:
           name: service_tokens
-          path: cdk-infra/
+          path: ./aws-pubsub/cdk-infra/
+
       - name: Synthesize CDK Stack
         run: |
           json_array=$(cat service_tokens.json)
@@ -251,7 +253,8 @@ jobs:
           echo "Final JSON Array:"
           cat tokens.json
           cdk synth -c configfile=tokens.json
-        working-directory: ./cdk-infra
+        working-directory: ./aws-pubsub/cdk-infra
+
       - name: Bootstrap CDK Stack
         run: |
           json_array=$(cat service_tokens.json)
@@ -260,7 +263,7 @@ jobs:
           echo "Final JSON Array:"
           cat service_tokens.json
           cdk bootstrap -c configfile=service_tokens.json
-        working-directory: ./cdk-infra
+        working-directory: ./aws-pubsub/cdk-infra
 
       - name: Deploy repoStackName to AWS
         run: |
@@ -270,7 +273,7 @@ jobs:
           echo "Final JSON Array:"
           cat service_tokens.json
           cdk deploy repoStackName --require-approval=never -c configfile=service_tokens.json
-        working-directory: ./cdk-infra
+        working-directory: ./aws-pubsub/cdk-infra
 
       - name: Login to Amazon ECR
         id: login-ecr
@@ -280,7 +283,7 @@ jobs:
         run: |
           for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
-            ecr_repo="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/$service_name"
+            ecr_repo="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{vars.AWS_DEFAULT_REGION}}.amazonaws.com/$service_name"
             echo "Building Docker image for $service_name"
             docker build -t "$ecr_repo:latest" "$service"
             echo "Pushing Docker image to ECR for $service_name"
@@ -295,16 +298,16 @@ jobs:
           echo "Final JSON Array:"
           cat service_tokens.json
           cdk deploy CdkInfraStack --require-approval=never -c configfile=service_tokens.json
-        working-directory: ./cdk-infra
+        working-directory: ./aws-pubsub/cdk-infra
 
-      - name: Update Cluster to get the most recent image
+      - name: Update fargate instances with most recent container images
         run: |
           for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             aws ecs update-service --cluster GROUP-CHAT-cluster --service $service_name --force-new-deployment
           done
 
-      - name: Retrieving the DNS for the services and updating the appIDs
+      - name: Retrieve DNS for the AWS ECS fargate instances
         run: |
           # Initialize an empty array
           json_array="[]"
@@ -320,15 +323,12 @@ jobs:
             echo "$alb_dns" >> $GITHUB_OUTPUT
             echo "$EOF" >> $GITHUB_OUTPUT
 
-
             # Create a JSON object with the service and ALB DNS
             json_object=$(jq -n --arg service "$service_name" --arg alb_dns "$alb_dns" \
                           '{service: $service, url: $alb_dns}')
 
             # Add the JSON object to the array
             json_array=$(echo $json_array | jq --argjson obj "$json_object" '. += [$obj]')
-
-
 
           done
           # Save the JSON array to a file
@@ -337,10 +337,9 @@ jobs:
           # Output the JSON array
           echo "JSON Array:"
           cat alb_services.json
+
       # Loop through the JSON array and extract values
-      - name:
-          Loop through the JSON array and extract ALB DNS and Service name,update
-          Catalyst API public Endpoint for each service
+      - name: Update Catalyst App IDs with AWS App Endpoints
         run: |
           # Read the JSON array from the file
           json_array=$(cat alb_services.json)
@@ -359,18 +358,19 @@ jobs:
               
           done
           # Save the JSON array to a file
-          echo $json_array | jq . > cdk-graphql-stack/alb_services.json
+          echo $json_array | jq . > ./aws-pubsub/cdk-graphql-stack/alb_services.json
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "alb_services<<$EOF" >> $GITHUB_OUTPUT
           echo "$json_array" >> $GITHUB_OUTPUT
           echo "$EOF" >> $GITHUB_OUTPUT
 
-          cat cdk-graphql-stack/alb_services.json
+          cat ./aws-pubsub/cdk-graphql-stack/alb_services.json
+
       - name: Upload alb_services.json
         uses: actions/upload-artifact@v4
         with:
           name: alb_services
-          path: cdk-graphql-stack/alb_services.json
+          path: ./aws-pubsub/cdk-graphql-stack/alb_services.json
 
   deploy-graphql-cdk-stack:
     runs-on: ubuntu-latest
@@ -385,15 +385,15 @@ jobs:
       - name: Install other dependencies
         run: |
           npm install
-        working-directory: ./cdk-graphql-stack
+        working-directory: ./aws-pubsub/cdk-graphql-stack
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@master
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
 
-      - name: Retrieving the DNS for the services and updating the appIDs
+      - name: Retrieving the DNS for the services and updating the App IDs
         run: |
           # Initialize an empty array
           json_array="[]"
@@ -432,7 +432,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: alb_services
-          path: cdk-graphql-stack/
+          path: ./aws-pubsub/cdk-graphql-stack/
       - name: Synthesize CdkGroupChatMicroserviceStack
         run: |
           json_array=$(cat alb_services.json)
@@ -441,7 +441,7 @@ jobs:
           echo "Final JSON Array:"
           cat tokens.json
           cdk synth -c configfile=tokens.json
-        working-directory: ./cdk-graphql-stack
+        working-directory: ./aws-pubsub/cdk-graphql-stack
       - name: Bootstrap CDK Stack
         run: |
           json_array=$(cat alb_services.json)
@@ -450,7 +450,7 @@ jobs:
           echo "Final JSON Array:"
           cat tokens.json
           cdk bootstrap -c configfile=tokens.json
-        working-directory: ./cdk-graphql-stack
+        working-directory: ./aws-pubsub/cdk-graphql-stack
 
       - name: Deploy CdkGroupChatMicroserviceStack to AWS
         run: |
@@ -460,4 +460,4 @@ jobs:
           echo "Final JSON Array:"
           cat tokens.json
           cdk deploy CdkGroupChatMicroserviceStack --require-approval=never -c configfile=tokens.json
-        working-directory: ./cdk-graphql-stack
+        working-directory: ./aws-pubsub/cdk-graphql-stack
