pipeline and doc updates

diff --git a/.github/workflows/aws-pubsub.yaml b/.github/workflows/aws-pubsub.yaml
--- a/.github/workflows/aws-pubsub.yaml
+++ b/.github/workflows/aws-pubsub.yaml
@@ -1,12 +1,9 @@
 name: Deploy AWS Pub/Sub Reference App Resources
 
-on:
-  push:
-    branches:
-      - master
+on: workflow_dispatch
 
 jobs:
-  setup-diagrid-project:
+  configure-diagrid-resources:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -26,64 +23,126 @@ jobs:
       # Log into Diagrid
       - name: Log Into Diagrid
         run: |
-          diagrid login --api-key ${{secrets.DIAGRID_API_KEY}}
+          diagrid login --api-key ${{secrets.CATALYST_API_KEY}}
       # Diagrid Version
       - name: Diagrid Version
         run: |
           diagrid version
-      - name: Create Diagrid Project
+      - name: Set Diagrid Project
         run: |
-          diagrid project create ${{secrets.DIAGRID_PROJECT}}
-      # Assign Diagrid Project
-      - name: Assign Diagrid Project
+          diagrid project use ${{vars.DIAGRID_PROJECT}} --api-key ${{secrets.CATALYST_API_KEY}}
+      - name: Create Diagrid App IDs
         run: |
-          diagrid project use ${{secrets.DIAGRID_PROJECT}} --api-key ${{secrets.DIAGRID_API_KEY}}
-      - name: Create Diagrid APP IDS
-        run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
-            diagrid appid create -p ${{secrets.DIAGRID_PROJECT}} $service_name
-            sleep 10
+
+            # Temporarily disable bash -e for the diagrid command
+            set +e
+            output=$(diagrid appid create -p test-aws "$service_name" 2>&1)
+            exit_code=$?
+            set -e
+
+            # Check if the output contains "Resource already exists"
+            if echo "$output" | grep -q "Resource already exists"; then
+              echo "Resource already exists for $service_name, skipping..."
+              continue
+            elif [ $exit_code -ne 0 ]; then
+              echo "An error occurred while creating appid for $service_name: $output"
+              exit 1
+            fi
+
+            sleep 5
           done
       - name: Creating Dynamodb Tables
         run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             echo "DynamoDB table name : ${service_name}-table"
             table_name="${service_name}-table"
-            aws dynamodb create-table --table-name $table_name --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
+            
+             # Temporarily disable bash -e for the table create command
+            set +e
+            # Capture output and errors from the AWS CLI command
+            output=$(aws dynamodb create-table \
+              --table-name "$table_name" \
+              --attribute-definitions AttributeName=key,AttributeType=S \
+              --key-schema AttributeName=key,KeyType=HASH \
+              --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 2>&1)
+            set -e
+            
+            # Check if the error is about the table already existing
+            if echo "$output" | grep -q "ResourceInUseException"; then
+              echo "Table already exists for $table_name, continuing..."
+              continue
+            elif [ $? -ne 0 ]; then
+              echo "An error occurred while creating table $table_name: $output"
+              exit 1
+            fi
+            
+            sleep 10
           done
+
       - name: Check App Status
         run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
-            diagrid appid get $service_name -p ${{secrets.DIAGRID_PROJECT}}
+            diagrid appid get $service_name -p ${{vars.DIAGRID_PROJECT}}
           done
 
       - name: Create Pub/Sub Component
         run: |
-          diagrid component create aws-pubsub --type pubsub.aws.snssqs --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ secrets.AWS_DEFAULT_REGION }} --project ${{ secrets.DIAGRID_PROJECT }}
+          # Temporarily disable bash -e for the component create command
+          set +e
+          output=$(diagrid component create aws-pubsub --type pubsub.aws.snssqs --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ secrets.AWS_DEFAULT_REGION }} --project ${{ vars.DIAGRID_PROJECT }})
+          set -e
+
+          # Check if the output contains "Resource already exists"
+          if echo "$output" | grep -q "Resource already exists"; then
+            echo "Resource already exists for component aws-pubsub, skipping..."
+            continue
+          elif [ $exit_code -ne 0 ]; then
+            echo "An error occurred while creating component aws-pubsub: $output"
+            exit 1
+          fi
+
       - name: Create State Component
         run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             table_name="${service_name}-table"
-            diagrid component create $table_name --type state.aws.dynamodb --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ secrets.AWS_DEFAULT_REGION }} --metadata table=$table_name --scopes $service_name --project ${{secrets.DIAGRID_PROJECT}}
-            sleep 30
+            
+             # Temporarily disable bash -e for the diagrid command
+            set +e
+            output=$(diagrid component create $table_name --type state.aws.dynamodb --metadata accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} --metadata secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} --metadata awsRegion=${{ secrets.AWS_DEFAULT_REGION }} --metadata table=$table_name --scopes $service_name --project ${{vars.DIAGRID_PROJECT}})
+            exit_code=$?
+            set -e
+
+            # Check if the output contains "Resource already exists"
+            if echo "$output" | grep -q "Resource already exists"; then
+              echo "Resource already exists for component $table_name, skipping..."
+              continue
+            elif [ $exit_code -ne 0 ]; then
+              echo "An error occurred while creating component $table_name: $output"
+              exit 1
+            fi
+            
+            sleep 10
+
           done
+
       - name: Check App Status
         run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
-            diagrid appid get $service_name -p ${{secrets.DIAGRID_PROJECT}}
+            diagrid appid get $service_name -p ${{vars.DIAGRID_PROJECT}}
           done
       - name: Creating subscriptions
         run: |
-          cat ./group_subs.yaml
-          diagrid subscriptions apply --wait --file ./group_subs.yaml
+          cat ./aws-pubsub/group_subs.yaml
+          diagrid subscriptions apply --wait --file ./aws-pubsub/group_subs.yaml
   upload-to-ecs:
     runs-on: ubuntu-latest
-    needs: setup-diagrid-project
+    needs: configure-diagrid-resources
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
@@ -97,33 +156,30 @@ jobs:
           # Download the latest Diagrid CLI from GitHub or direct source
           curl -o- https://downloads.diagrid.io/cli/install.sh | bash
           sudo mv ./diagrid /usr/local/bin
-      # Log into diagrid
-      - name: Log Into Diagrid
+      - name: Log in to Diagrid
         run: |
-          diagrid login --api-key ${{secrets.DIAGRID_API_KEY}}
-      # Diagrid Version
+          diagrid login --api-key ${{secrets.CATALYST_API_KEY}}
       - name: Diagrid Version
         run: |
           diagrid version
-      # Assign Diagrid Project
-      - name: Assign Diagrid Project
+      - name: Use Diagrid Project
         run: |
-          diagrid project use ${{secrets.DIAGRID_PROJECT}} --api-key ${{secrets.DIAGRID_API_KEY}}
+          diagrid project use ${{vars.DIAGRID_PROJECT}} --api-key ${{secrets.CATALYST_API_KEY}}
 
-      # Retrieve apiTokens and URLs for all project services
-      - name: Retrieve apiToken for each service,http and grpc urls for the project
+      # Retrieve API Tokens and URLs for all App IDs
+      - name: Retrieve API Token for each service, http and grpc urls for the project
         run: |
           # Initialize an empty array for the final output
           json_array="[]"
-          
+
           # Fetch the project details to extract http_url and grpc_url
-          diagrid_project_output=$(diagrid project get ${{secrets.DIAGRID_PROJECT}})
-          
+          diagrid_project_output=$(diagrid project get ${{vars.DIAGRID_PROJECT}})
+
           # Extract the HTTP and GRPC URLs from the project output
           http_url=$(echo "$diagrid_project_output" | grep -A 1 "http:" | grep "url:" | awk '{print $2}')
           grpc_url=$(echo "$diagrid_project_output" | grep -A 1 "grpc:" | grep "url:" | awk '{print $2}')
-          
-          for service in ./services/*/ ; do
+
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             
             # Fetch the Diagrid app identity information in JSON format
@@ -154,7 +210,7 @@ jobs:
             # Add the JSON object to the array
             json_array=$(echo $json_array | jq --argjson obj "$json_object" '. += [$obj]')
           done
-          
+
           # Save the JSON array to a file
           echo $json_array | jq . > cdk-infra/service_tokens.json
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
@@ -163,7 +219,6 @@ jobs:
           echo "$EOF" >> $GITHUB_OUTPUT
 
           cat cdk-infra/service_tokens.json
-
 
       - name: Upload service_tokens.json
         uses: actions/upload-artifact@v4
@@ -223,7 +278,7 @@ jobs:
 
       - name: Build and push Docker images
         run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             ecr_repo="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/$service_name"
             echo "Building Docker image for $service_name"
@@ -244,7 +299,7 @@ jobs:
 
       - name: Update Cluster to get the most recent image
         run: |
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             aws ecs update-service --cluster GROUP-CHAT-cluster --service $service_name --force-new-deployment
           done
@@ -253,32 +308,32 @@ jobs:
         run: |
           # Initialize an empty array
           json_array="[]"
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             alb_name=$(basename "$service")-ALB
             alb_dns=$(aws elbv2 describe-load-balancers --names $alb_name --query "LoadBalancers[0].DNSName" --output text)
             echo "ALB DNS: $alb_dns"
             echo "Service name is : $service_name"
-  
+
             EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
             echo "alb_dns<<$EOF" >> $GITHUB_OUTPUT
             echo "$alb_dns" >> $GITHUB_OUTPUT
             echo "$EOF" >> $GITHUB_OUTPUT
-  
-  
+
+
             # Create a JSON object with the service and ALB DNS
             json_object=$(jq -n --arg service "$service_name" --arg alb_dns "$alb_dns" \
                           '{service: $service, url: $alb_dns}')
-  
+
             # Add the JSON object to the array
             json_array=$(echo $json_array | jq --argjson obj "$json_object" '. += [$obj]')
-  
-  
-  
+
+
+
           done
           # Save the JSON array to a file
           echo $json_array | jq . > alb_services.json
-  
+
           # Output the JSON array
           echo "JSON Array:"
           cat alb_services.json
@@ -289,17 +344,17 @@ jobs:
         run: |
           # Read the JSON array from the file
           json_array=$(cat alb_services.json)
-  
+
           # Loop through the array and extract service and alb_dns
           for row in $(echo "${json_array}" | jq -r '.[] | @base64'); do
               _jq() {
                 echo ${row} | base64 --decode | jq -r ${1}
               }
-  
+
               service=$(_jq '.service')
               alb_dns=$(_jq '.url')
-              diagrid appid update $service --app-endpoint "http://$alb_dns" -w --api-key ${{secrets.DIAGRID_API_KEY}}
-  
+              diagrid appid update $service --app-endpoint "http://$alb_dns" -w --api-key ${{secrets.CATALYST_API_KEY}}
+
               echo "Service: $service, ALB DNS: $alb_dns"
               
           done
@@ -342,7 +397,7 @@ jobs:
         run: |
           # Initialize an empty array
           json_array="[]"
-          for service in ./services/*/ ; do
+          for service in ./aws-pubsub/services/*/ ; do
             service_name=$(basename "$service")
             alb_name=$(basename "$service")-ALB
             alb_dns=$(aws elbv2 describe-load-balancers --names $alb_name --query "LoadBalancers[0].DNSName" --output text)
